<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Grid.Core\Grid.Core.csproj" />
    <ProjectReference Include="..\Grid.GtaV.Knowledge\Grid.GtaV.Knowledge.csproj" />
  </ItemGroup>
</Project>
