$ErrorActionPreference='Stop'
$gameRoot=Split-Path -Parent $PSScriptRoot;$scriptsRoot=Split-Path -Parent (Split-Path -Parent $gameRoot)
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function Assert-Equal($Expected,$Actual,[string]$Message){if($Expected -ne $Actual){throw "$Message Expected '$Expected', actual '$Actual'."}}
function Assert-Throws([scriptblock]$Action,[string]$Pattern,[string]$Message){try{&$Action;throw "$Message Expected '$Pattern'."}catch{if($_.Exception.Message -notmatch $Pattern){throw "$Message Unexpected: $($_.Exception.Message)"}}}
$temp=Join-Path $env:TEMP ('grid-mod-state-'+[Guid]::NewGuid().ToString('N'));$profileRoot=Join-Path $temp 'profiles\Fixture';New-Item -ItemType Directory -Path $profileRoot -Force|Out-Null
$modlist=Join-Path $profileRoot 'modlist.txt';$utf8Bom=[Text.UTF8Encoding]::new($true);[IO.File]::WriteAllText($modlist,"# This file was automatically generated by Mod Organizer.`r`n+Enabled Mod`r`n-Disabled Mod`r`n*Skyrim.esm`r`n+Visuals_separator`r`n",$utf8Bom)
$executor=Join-Path $gameRoot 'mo2\Set-GridModState.ps1';$bridge=Join-Path $gameRoot 'health\actions\Invoke-GridConfirmedModStateChange.ps1'
try{
 Assert-Throws {&$executor -ModName 'Enabled Mod' -Action Disable -Mo2Root $temp -Profile Fixture} 'AuthorizedProposalRequired' 'Direct mutation must refuse.'
 Assert-Throws {&$executor -ModName 'Skyrim.esm' -Action Disable -Mo2Root $temp -Profile Fixture -WhatIf} 'AuthorizedProposalRequired' 'Foreign direct mutation must refuse before action.'
 $input=[ordered]@{schemaVersion=1;userConfirmed=$true;confirmedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');installationId='fixture';mo2Root=$temp;profile='Fixture';modName='Enabled Mod';expectedCurrentState='Enabled';desiredState='Disabled';gridDataRoot=(Join-Path $temp 'grid-data');actorId='actor.fixture';sessionId='session.fixture'}
 $inputPath=Join-Path $temp 'request.json';$input|ConvertTo-Json|Set-Content -LiteralPath $inputPath -Encoding UTF8
 $before=(Get-FileHash -LiteralPath $modlist -Algorithm SHA256).Hash;$whatIfResult=&$bridge -InputJsonPath $inputPath -WhatIf|ConvertFrom-Json
 Assert-Equal 'Incomplete' $whatIfResult.ProposalStatus 'WhatIf must validate the complete authorized route without mutating.';Assert-True(-not$whatIfResult.Execution.Changed)'WhatIf must not change the entry.';Assert-Equal $before (Get-FileHash -LiteralPath $modlist -Algorithm SHA256).Hash 'WhatIf must preserve modlist.txt byte-for-byte.'
 function global:Get-Process { @() }
 $input.confirmedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');$input|ConvertTo-Json|Set-Content -LiteralPath $inputPath -Encoding UTF8
 $result=&$bridge -InputJsonPath $inputPath|ConvertFrom-Json
 Assert-Equal 'Verified' $result.ProposalStatus 'Confirmed transition must verify.';Assert-Equal 'Disabled' $result.Execution.State 'Entry must be disabled.';Assert-True $result.Execution.Changed 'Entry must change.';Assert-True (Test-Path -LiteralPath $result.Execution.Backup -PathType Leaf) 'Backup must exist.'
 $bytes=[IO.File]::ReadAllBytes($modlist);Assert-True($bytes[0]-eq0xEF-and$bytes[1]-eq0xBB-and$bytes[2]-eq0xBF)'UTF-8 BOM must be preserved.'
 $text=[IO.File]::ReadAllText($modlist);Assert-True($text.Contains("-Enabled Mod`r`n"))'Only the marker must change.';Assert-True($text.Contains("-Disabled Mod`r`n"))'Other rows must remain.'
 $input.expectedCurrentState='Enabled';$input.desiredState='Disabled';$input.confirmedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');$input|ConvertTo-Json|Set-Content -LiteralPath $inputPath -Encoding UTF8
 Assert-Throws {&$bridge -InputJsonPath $inputPath -WhatIf} 'StaleModState' 'Stale displayed state must refuse.'
 $foreign=&$executor -ModName 'Skyrim.esm' -Action Status -Mo2Root $temp -Profile Fixture -PassThru;Assert-Equal 'Foreign' $foreign.State 'Foreign entries must remain distinguishable and protected.'
 Write-Host 'PASS: confirmed mod state changes are exact, one-use authorized, backed up, verified, stale-safe, foreign-safe, and encoding-preserving.'
}finally{Remove-Item Function:\global:Get-Process -ErrorAction SilentlyContinue;if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}}
